# Generated by Django 4.1.4 on 2022-12-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='litter',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
