# Generated by Django 4.1.4 on 2022-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_main_image_alter_dog_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('EB', 'English Bulldog'), ('FB', 'French Bulldog')], default='EB', max_length=2),
        ),
    ]
